import React,{useState,useEffect} from 'react';
import {Routes,Route,Navigate,useNavigate,Link} from 'react-router-dom';
import {api,saveSession,user,logout} from './api';

const roles={SYSTEM_ADMIN:'/admin',NORMAL_USER:'/stores',STORE_OWNER:'/owner'};
function Protected({children,role}){const u=user();if(!u)return <Navigate to="/login"/>;if(role&&u.role!==role)return <Navigate to={roles[u.role]||'/login'}/>;return children}
function Layout({children}){const nav=useNavigate(),u=user();return <><header><b>Store Rating</b><nav><span>{u?.name}</span><Link to={roles[u?.role]||'/'}>Dashboard</Link><Link to="/password">Change Password</Link><button onClick={()=>{logout();nav('/login')}}>Logout</button></nav></header><main>{children}</main></>}
function Login(){const [form,setForm]=useState({email:'',password:''}),[err,setErr]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await api.post('/auth/login',form);saveSession(r.data);nav(roles[r.data.user.role]);}catch(e){setErr(e.response?.data?.message||'Login failed')}};return <div className="auth"><h1>Login</h1><form onSubmit={submit}><input placeholder="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button>Login</button>{err&&<p className="error">{err}</p>}</form><p>New user? <Link to="/signup">Sign up</Link></p><p className="hint">Demo: admin@example.com / Admin@123</p></div>}
function Signup(){const [f,setF]=useState({name:'',email:'',address:'',password:''}),[err,setErr]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{const r=await api.post('/auth/signup',f);saveSession(r.data);nav('/stores')}catch(e){setErr(e.response?.data?.message||'Signup failed')}};return <div className="auth"><h1>Normal User Signup</h1><form onSubmit={submit}>{['name','email','address','password'].map(k=><input key={k} placeholder={k[0].toUpperCase()+k.slice(1)} type={k==='password'?'password':k==='email'?'email':'text'} required value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button>Sign Up</button>{err&&<p className="error">{err}</p>}</form><p>Already registered? <Link to="/login">Login</Link></p></div>}
function Password(){const [f,setF]=useState({currentPassword:'',newPassword:''}),[msg,setMsg]=useState('');const submit=async e=>{e.preventDefault();try{await api.put('/auth/password',f);setMsg('Password updated successfully')}catch(e){setMsg(e.response?.data?.message||'Update failed')}};return <Layout><section className="card"><h2>Change Password</h2><form onSubmit={submit}><input type="password" placeholder="Current password" required onChange={e=>setF({...f,currentPassword:e.target.value})}/><input type="password" placeholder="New password" required onChange={e=>setF({...f,newPassword:e.target.value})}/><button>Update</button></form><p>{msg}</p></section></Layout>}
function Stores(){const [rows,setRows]=useState([]),[q,setQ]=useState({name:'',address:''}),[msg,setMsg]=useState('');const load=async()=>setRows((await api.get('/stores',{params:q})).data);useEffect(()=>{load()},[]);const rate=async(id,current)=>{const value=prompt('Enter rating from 1 to 5',current||'');if(value===null)return;try{await (current?api.put(`/stores/${id}/rating`,{rating:Number(value)}):api.post(`/stores/${id}/rating`,{rating:Number(value)}));load()}catch(e){setMsg(e.response?.data?.message||'Could not save rating')}};return <Layout><section className="card"><h2>Stores</h2><div className="filters"><input placeholder="Search by Name" onChange={e=>setQ({...q,name:e.target.value})}/><input placeholder="Search by Address" onChange={e=>setQ({...q,address:e.target.value})}/><button onClick={load}>Search</button></div>{msg&&<p>{msg}</p>}<table><thead><tr><th>Store Name</th><th>Address</th><th>Overall Rating</th><th>Your Rating</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.address}</td><td>{r.overall_rating??'No ratings'}</td><td>{r.user_rating??'-'}</td><td><button onClick={()=>rate(r.id,r.user_rating)}>{r.user_rating?'Modify':'Rate'}</button></td></tr>)}</tbody></table></section></Layout>}
function Admin(){const [dash,setDash]=useState({}),[users,setUsers]=useState([]),[stores,setStores]=useState([]);const [uf,setUf]=useState({});const load=async()=>{setDash((await api.get('/admin/dashboard')).data);setUsers((await api.get('/admin/users',{params:uf})).data);setStores((await api.get('/admin/stores')).data)};useEffect(()=>{load()},[]);return <Layout><h2>Admin Dashboard</h2><div className="stats"><div>Users <b>{dash.users}</b></div><div>Stores <b>{dash.stores}</b></div><div>Ratings <b>{dash.ratings}</b></div></div><section className="card"><h3>Users</h3><div className="filters"><input placeholder="Name" onChange={e=>setUf({...uf,name:e.target.value})}/><input placeholder="Email" onChange={e=>setUf({...uf,email:e.target.value})}/><input placeholder="Address" onChange={e=>setUf({...uf,address:e.target.value})}/><select onChange={e=>setUf({...uf,role:e.target.value})}><option value="">All roles</option><option>SYSTEM_ADMIN</option><option>NORMAL_USER</option><option>STORE_OWNER</option></select><button onClick={async()=>setUsers((await api.get('/admin/users',{params:uf})).data)}>Filter</button></div><table><thead><tr><th>Name</th><th>Email</th><th>Address</th><th>Role</th><th>Rating</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.address}</td><td>{u.role}</td><td>{u.rating??'-'}</td></tr>)}</tbody></table></section><section className="card"><h3>Stores</h3><table><thead><tr><th>Name</th><th>Email</th><th>Address</th><th>Rating</th></tr></thead><tbody>{stores.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.email}</td><td>{s.address}</td><td>{s.rating??'-'}</td></tr>)}</tbody></table></section></Layout>}
function Owner(){const [data,setData]=useState([]);useEffect(()=>{api.get('/owner/dashboard').then(r=>setData(r.data))},[]);return <Layout><h2>Store Owner Dashboard</h2>{data.map(s=><section className="card" key={s.id}><h3>{s.name}</h3><p>Average Rating: <b>{s.average_rating??'No ratings'}</b></p><table><thead><tr><th>User</th><th>Email</th><th>Address</th><th>Rating</th></tr></thead><tbody>{s.users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.address}</td><td>{u.rating}</td></tr>)}</tbody></table></section>)}</Layout>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/password" element={<Protected><Password/></Protected>}/><Route path="/stores" element={<Protected role="NORMAL_USER"><Stores/></Protected>}/><Route path="/admin" element={<Protected role="SYSTEM_ADMIN"><Admin/></Protected>}/><Route path="/owner" element={<Protected role="STORE_OWNER"><Owner/></Protected>}/><Route path="*" element={<Navigate to={user()?roles[user().role]:'/login'}/>}/></Routes>}
